!3/13/18: cleaned up a few more comments
!7/9/17: This code was generated by Emily Zakem and submitted as supporting information for the article "Ecological control of nitrite in the upper ocean."
!Note: As written, this model has options for 3 different P types and 3 zooplankton types, though only 1 for each is switched on: "p3" and "zoo3." It also has a placeholder in for another bacterial type ("bo_pa") though it is excluded in the equations

PROGRAM MGbasedonEZM

IMPLICIT NONE

INTEGER,PARAMETER :: ndays=8e2, &
	Hp=2000, & !change this scale below too
	dz=5, &  
	nz=Hp/dz
REAL*8,PARAMETER :: dt=0.02D0, & 
	!ndays=0.05D0, & !for fractions of days
	H=2D3, & 
	!
	!PHYSICAL params:
	euz=25D0, & !m euphotic zone (absorption by water molecules) 
	mlz=50D0, & !m mixed layer depth 
	o2sat=.2121D0, & !mol/m3 from calc_oxsat(25+273,35) in matlab. WOCE clim-avg surf T at 10S, E. Pac.
	Kgast=3D-5, & !m/s
	!deep oxygen relaxation
	o2satdeep=0.2D0, & !mol/m3, avg (for ~7 C) and 35
	t_o2relax=1D-2, & !1/day 
	kappazmin=5D-5, & !m2/s 
	kappazmax=1D-3, & !m2/s 
	Ws=10D0, & !m/day (range is 1-100) 
    phi=5.59D3, & !ammonium inhibition parameter
    !
	!BACTERIA METABOLISMS: 
	!
	!Bo: Aerobic Heterotroph
	yd_bo=0.14D0, & !mol cells/mol Detritus - aerobic bacteria yield
	yo_bo=yd_bo/20D0*4D0/(1D0-yd_bo), & !mol cells/mol O2 -where cells have 1mol N 
	enh4_bo=(1D0/yd_bo-1D0), & !production of ammonia per mol cells produced
	pd_max= 1D0, & !1/day - normalized max detritus uptake to match nitrate max uptake
	kd= 0.05D-3, &
	po_coef=2329100D0, & !m3/mol/day -
	!
	!Bnh4: Ammonia oxidizer
    ynh4_bnh4=1D0/112D0, & 
    yo_bnh4=1D0/162D0, &
    eno2_bnh4=(1D0/ynh4_bnh4-1D0), & 
    pn_max= 50.8D0, &
    pna=0.0169D0, &
	kn= 0.133D-3, & !mol DIN/m3  0.133D-3
    kna=2.5D0, &
    knb=0.39D0, &
    !lightinhibited parameters
	!
	!Bno2: Nitrite oxidizer
    yno2_bno2=1D0/334D0, &
    yo_bno2=1D0/162D0, &
	eno3_bno2=(1D0/yno2_bno2-1D0), & 
	pn_max_noo= 40.3D0, & 
    pn_nooa=0.01969, &
	kn_noo= 0.168D-3, & 
    !kn*2.1544D0
    kn_nooa=2.5, &
    kn_noob=0.39, &
    !lightinhibited parameters
	!
	!P: phytoplankton
	umaxp=0.515D0, & !1/d -Ward 2014: 1*V^-0.15 for d=0.6 for Pro. max growth rate for p at 20C 0.515D0,
	Iinmax=1400D0, & !W/m2 1400
	knh4p3= 0.1D-3, & !mol/m3 Litchman scaling, with aV^b with a for knh4 from Ward 2014  0.0018D-3
	kno2p3= 1D-3, & !mol/m3 Litchman 0.0036D-3
	kno3p3= 1D-3, & !mol/m3 Litchman 0.0036D-3
	knh4p2=1D-3, &
	kno2p2=0.2D-3, &
	kno3p2=0.2D-3, &
    kup=1D-5, & !uptake threshold for NH4, NO2 and NO3
    !zeta1=1D-1, &
    !zeta2=1D-1, &
    !zeta3=1D-1, &
    !zeta4=1D0, &
	!koxid=1D-10, &
    chl2cmax=0.2D0, & !mg Chl/mmol C from Dutk 2015 
    chl2cmin=0.02D0, & !mg Chl/mmol C 
    phimaxs=40D0, & !mmol C/mol photons/Ein  -quantum yield (mol C/mol photons)
    phimaxl=40d0, & !quantum yield for large phytoplankton
    a_chl=0.01D0, & !m2/mg chl a -absorption parameter by chlorophyll 
    a_chlD=0.04D3, & !m2/g chl a -for light attenutation: chlorophyll plus CDOM
	convI=2.77D18/6.02D23*86400D0, & !from W/m2 to Ein/m2/d 2.77e18[quanta/W/s]*1/6.02e23[Einstein/quanta]. from MBARI: http://www3.mbari.org/bog/nopp/par.html
    !
    !Zooplankton:
    gmax=1D0, & 
    kg=1D-3, & !mol/m3
    gam=0.5D0, &
    !
	!GRAZINGandMORTALITy:
    mlin=5D-2, & !linear mortality for b
	mlinl=5D-2, & !linear mortality for lp
    mlins=5D-2, & !linear mortality for b and sp
	mquad=0D3, & !quadratic mortality for b and p
	mz=0.7D3, & !quadratic mortality for Z 0.7D3
	!
	!Oxygen ratio for pp production and zoo consumption:
    RredO=467D0/4D0/16D0, &
    !Temperature:
    TempAeArr = -4D3, & !-4D3
    TempAeArrP = -8D3, & !-4D3
    TemprefArr = 293.15D0, &    
    Tkel = 273.15D0, &
    TempCoeffArr = 0.8D0


INTEGER :: t,mlboxes,j,i,jc,nt,startSS,ind,recordDaily,dailycycle,dommodel,onep
REAL*8 :: zm(nz) = (/(j,j=0+dz/2,Hp-dz/2, dz)/)
REAL*8 :: z(nz+1) = (/(j,j=0,Hp, dz)/)
REAL*8 :: koverh, distn, adv, diff, cputime,dayint,dayint2,Iin
REAL*8,DIMENSION(:),ALLOCATABLE :: time, burial
REAL*8,DIMENSION(:,:),ALLOCATABLE :: sumall
REAL*8,DIMENSION(nz+1) :: w,wd,Kz,KzO,KzP
REAL*8,DIMENSION(nz+4) :: eqmask,inmask,Iz,nutri, & 
	u_bo,u_bo_pa,u_bnh4,u_bno2,u_p1,u_p2,u_p3,u_p3nolim,bt,pt,btsq,ptsq,g,g2,g3, &
    !zeta1,zeta2,zeta3,zeta4, &
    Biot,Chlt,po,pd,pdom,pnh4,pno2,pnh4b,pno2b,pno3,Temp,Q10r,TempFun,TempFunP, &  
	limnh4p3,limno2p3,limno3p3,inhibnh4, & !explicit limits to ease equations later
	limnh4p2,limno2p2,limno3p2, &
	limnh4b,limno2b, & !different n lims for the b
    nlimtotp2,nlimtotp3, &
	nh4,no2,no3,ntot,o,bo,bo_pa,bnh4,bno2,d,dom,zoo,zoo2,zoo3,p1,xp1,p2,xp2,p3,xp3, &
	knh4A,knh4B,knh4C,knh4D,nh4A,nh4B,nh4C, &
	kno2A,kno2B,kno2C,kno2D,no2A,no2B,no2C, &
	kno3A,kno3B,kno3C,kno3D,no3A,no3B,no3C, &
	koA,koB,koC,koD,oA,oB,oC, &
	kboA,kboB,kboC,kboD,boA,boB,boC, &
	kbo_paA,kbo_paB,kbo_paC,kbo_paD,bo_paA,bo_paB,bo_paC, &
	kbnh4A,kbnh4B,kbnh4C,kbnh4D,bnh4A,bnh4B,bnh4C, &
	kbno2A,kbno2B,kbno2C,kbno2D,bno2A,bno2B,bno2C, &
	kdA,kdB,kdC,kdD,dA,dB,dC,kdomA,kdomB,kdomC,kdomD,domA,domB,domC, &
	kzooA,kzooB,kzooC,kzooD,zooA,zooB,zooC, &
	kzoo2A,kzoo2B,kzoo2C,kzoo2D,zoo2A,zoo2B,zoo2C, &
	kzoo3A,kzoo3B,kzoo3C,kzoo3D,zoo3A,zoo3B,zoo3C, &
	kp1A,kp1B,kp1C,kp1D,p1A,p1B,p1C, &
	kxp1A,kxp1B,kxp1C,kxp1D,xp1A,xp1B,xp1C, &
	kp2A,kp2B,kp2C,kp2D,p2A,p2B,p2C, &
	kxp2A,kxp2B,kxp2C,kxp2D,xp2A,xp2B,xp2C, &
	kp3A,kp3B,kp3C,kp3D,p3A,p3B,p3C, &
	kxp3A,kxp3B,kxp3C,kxp3D,xp3A,xp3B,xp3C, &
    no3uptakeP,no2emitP, p3diff, p2diff, dsinking, &
    knh4diff,kno2diff,kno3diff, &
    PC1,PCmax1,PC2,PCmax2,PC3,PCmax3,a_Is,a_Il,chl2c,chl2c_p1,chl2c_p2,chl2c_p3, &!for Chl:C model
    knh4zoo,knh4_het,knh4_nh4oxid,P3uptakeNH4,P2uptakeNH4, &
    kno2_nh4oxid,kno2_no2oxid,kno2_p3use,kno2_p2use, &
    kno3_no2oxid,P3uptakeNO3,P2uptakeNO3, P3uptakeNO2,P2uptakeNO2, &
    p3growth,p2growth,p3mortality,p2mortality,p3grazed,p2grazed, &
	nh4tt_1, nh4tt_2, no2tt_1, no2tt_2, no3tt_1, no3tt_2

startSS=0 !set to 0 to define IC within this script 
dayint=10D0 !for recording frequency for resolved 1D for movies
dayint2=10D0 !for recording output frequency (replaced every time)
dailycycle=1 !for time-variant model resolving daily light cycle
recordDaily=0 !for recording each dt for movies of daily cycle
onep=2 !make just one pp type (P3)

kdA(:)=0D0
kdB(:)=0D0
kdC(:)=0D0
kdD(:)=0D0
!
kdomA(:)=0D0
kdomB(:)=0D0
kdomC(:)=0D0
kdomD(:)=0D0
!
knh4A(:)=0D0
knh4B(:)=0D0
knh4C(:)=0D0
knh4D(:)=0D0
kno2A(:)=0D0
kno2B(:)=0D0
kno2C(:)=0D0
kno2D(:)=0D0
kno3A(:)=0D0
kno3B(:)=0D0
kno3C(:)=0D0
kno3D(:)=0D0
!
kboA(:)=0D0
kboB(:)=0D0
kboC(:)=0D0
kboD(:)=0D0
!
kbnh4A(:)=0D0
kbnh4B(:)=0D0
kbnh4C(:)=0D0
kbnh4D(:)=0D0
kbno2A(:)=0D0
kbno2B(:)=0D0
kbno2C(:)=0D0
kbno2D(:)=0D0
koA(:)=0D0
koB(:)=0D0
koC(:)=0D0
koD(:)=0D0
!
kzooA(:)=0D0
kzooB(:)=0D0
kzooC(:)=0D0
kzooD(:)=0D0
kzoo2A(:)=0D0
kzoo2B(:)=0D0
kzoo2C(:)=0D0
kzoo2D(:)=0D0
kzoo3A(:)=0D0
kzoo3B(:)=0D0
kzoo3C(:)=0D0
kzoo3D(:)=0D0
!
kp1A(:)=0D0
kp1B(:)=0D0
kp1C(:)=0D0
kp1D(:)=0D0
!
kp2A(:)=0D0
kp2B(:)=0D0
kp2C(:)=0D0
kp2D(:)=0D0
!
kp3A(:)=0D0
kp3B(:)=0D0
kp3C(:)=0D0
kp3D(:)=0D0
!

print*,'Run for total n of days:';print*,ndays
print*,'1D version'
print*,'nz is:'; print*,nz

nt=ndays/dt

print*,'Number of days:'
print*,ndays
print*,'Number of timesteps:'
print*,nt

mlboxes=100D0/dz !discrete n of boxes in the mixed layer, close to 100m total sum
koverh=Kgast/100D0/mlboxes*3600D0*24D0 !gas transfer coefficient for each of the n boxes comprising the ml

ALLOCATE(time(nt))
ALLOCATE(burial(nt+1))
ind=ndays/dayint2
ALLOCATE(sumall(ind,17))

!sinking speed for detritus
wd(:)=Ws
wd(1)=0D0
wd(nz+1)=0D0

!1D model: no advection for other tracers
	w(:)=0D0
	wd=wd+w; !vertical velocity combination for detritus

!Diffusion:
Kz=(kappazmax*exp(-(z)/mlz)+kappazmin+1D-2*exp((z-H)/100D0))*3600D0*24D0 !larger at bottom boundary, too

Temp(:)=0D0 
Temp(3:nz+2)=12D0*exp(-zm/150D0)+12D0*exp(-zm/500D0)+2D0
TempFun = TempCoeffArr*exp(TempAeArr*(1D0/(Temp+Tkel)-1D0/TemprefArr))
TempFunP = TempCoeffArr*exp(TempAeArrP*(1D0/(Temp+Tkel)-1D0/TemprefArr))

KzO=Kz
KzP=Kz
KzO(1)=0D0
!KzP(1)=1D2
!for an open boundary: a sink for oxygen:
!KzO(nz+1)=(kappazmin+1D-2*exp((H-H)/100D0))*3600D0*24D0 
!for a closed boundary: a fixed o2
KzO(nz+1)=0D0

Kz(1)=0D0
Kz(nz+1)=0D0
!KzP(nz+1)=0D0

eqmask(:)=0D0
eqmask(3:mlboxes+2)=1D0; !mask for air-sea equilibration

inmask(:)=0D0
inmask(3:nz+2)=1D0 !mask to zero out ghost cells for tracers and other quantities affecting tracers

!import previous steady state as IC:

if (startSS.eq.1) then

		OPEN(UNIT=3,FILE='ICfiles/nh4_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (nh4(J),J=1,nz+4)
		CLOSE(3)
		
		OPEN(UNIT=3,FILE='ICfiles/no2_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (no2(J),J=1,nz+4)
		CLOSE(3)
		
		OPEN(UNIT=3,FILE='ICfiles/no3_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (no3(J),J=1,nz+4)
		CLOSE(3)

		OPEN(UNIT=3,FILE='ICfiles/d_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (d(J),J=1,nz+4)
		CLOSE(3)
		
		OPEN(UNIT=3,FILE='ICfiles/dom_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (d(J),J=1,nz+4)
		CLOSE(3)

		OPEN(UNIT=3,FILE='ICfiles/o_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (o(J),J=1,nz+4)
		CLOSE(3)

		OPEN(UNIT=3,FILE='ICfiles/bo_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (bo(J),J=1,nz+4)
		CLOSE(3)

		OPEN(UNIT=3,FILE='ICfiles/bnh4_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (bnh4(J),J=1,nz+4)
		CLOSE(3)
		
		OPEN(UNIT=3,FILE='ICfiles/bno2_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (bno2(J),J=1,nz+4)
		CLOSE(3)

		OPEN(UNIT=3,FILE='ICfiles/zoo_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (zoo(J),J=1,nz+4)
		CLOSE(3)
		
		OPEN(UNIT=3,FILE='ICfiles/zoo2_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (zoo2(J),J=1,nz+4)
		CLOSE(3)
		
		OPEN(UNIT=3,FILE='ICfiles/zoo3_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (zoo3(J),J=1,nz+4)
		CLOSE(3)
		
        OPEN(UNIT=3,FILE='ICfiles/p1_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (p1(J),J=1,nz+4)
		CLOSE(3)

        OPEN(UNIT=3,FILE='ICfiles/p2_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (p2(J),J=1,nz+4)
		CLOSE(3)

        OPEN(UNIT=3,FILE='ICfiles/p3_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (p3(J),J=1,nz+4)
		CLOSE(3)

else
		!!Initial Conditions from simple distributions (may break now bc of steep gradients):
		nh4(:)=0.05D-3
        nh4(1:2)=1D-4
		no2(:)=0.05D-3
		bo(:)=inmask*2D-4
		bnh4(:)=inmask*0.12D-12! inmask*1D-7% one AOO cell % assumed that 1 cell/L
		bno2(:)=inmask*1.2D-12! inmask*1D-7%one NOO cell %assume that 1 cell/L
        p1(:)=inmask*1D-7
		p2(:)=inmask*0.68D-12  
        p3(:)=inmask*0.68D-12 !cell quota of Pro is estimated to be 0.68 fmol N per cell, thus 1 cell/L here
        !p3(2)=1D-7
        !p3(1)=0D0

		o(:)=0.2D0!inmask*0.2D0 !mol/m3 crude estimate 
		zoo(:)=inmask*1D-6
		zoo2(:)=inmask*1D-6
		zoo3(:)=inmask*2D-5
		
        !no3(3:nz+2)=0.03D0*(1D0-exp(-(zm+300D0)/200D0)) ! n increases with depth
        !no3(:)=250D-6
        !no3(:)=0.03D0
        OPEN(UNIT=3,FILE='ICfiles/no3_fSS.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
		read(3,*) (no3(J),J=1,nz+4)
        !print*, no3
		!CLOSE(3)
        

		d(:)=0D0 !start with none

end if

if (onep.eq.1) then
    !take out p1 and p2:
    p1(:)=0D0
    p2(:)=0D0
else if (onep.eq.2) then
    p1(:)=0D0 
end if

!take out zoo and zoo2
zoo(:)=0D0
zoo2(:)=0D0
!zoo3(:)=0D0

OPEN(UNIT=5,FILE='time_record.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)

if (recordDaily.eq.1) then

OPEN(UNIT=5,FILE='Iin.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)

OPEN(UNIT=5,FILE='Iz.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)

OPEN(UNIT=5,FILE='knh4zoo.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)

OPEN(UNIT=5,FILE='time_all.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)

OPEN(UNIT=5,FILE='nh4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',STATUS='REPLACE')
CLOSE(5)	
OPEN(UNIT=5,FILE='no2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',STATUS='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='no3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',STATUS='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='d_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='dom_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='o_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)	
OPEN(UNIT=5,FILE='bo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)	
OPEN(UNIT=5,FILE='bo_pa_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)	
OPEN(UNIT=5,FILE='bnh4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='bno2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='ubo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='ubnh4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='ubno2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='up_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='zoo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='zoo2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='zoo3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='p1_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='xp1_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='p2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='p3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='xp2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='xp3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='Iz_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='chl2c_p3.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='chl2c_p2.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)
OPEN(UNIT=5,FILE='Chlt_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',status='REPLACE')
CLOSE(5)

end if 


print *,'Starting time loop:'
do t=1,nt


!LIGHT:
if (dailycycle.eq.1) then !Incoming light daily cycle:
    Iin=Iinmax/2D0*(cos(t*dt*2D0*3.1416D0)+1D0)
else !No daily cycle:
    Iin=Iinmax/2D0
end if

!chl impact on light:
Chlt=(p1*chl2c_p1+p2*chl2c_p2+p3*chl2c_p3)*6.6D0 !molN/m3 *mgChl/mmolC *5molC/molN = gChl

do j=1,nz
    Iz(j+2)=Iin*exp(-zm(j)*(1/euz+sum(Chlt(3:j+2)*a_chlD))) !this one sums the k at each depth
end do

i=dayint2*1000
j=t*dt*1000

if (MOD(j,i).eq.0) then
	!trace the integral:
	ind=t*dt/dayint2
	
	time(ind)=(t-1)*dt 

	ntot=nh4+no2+no3
	
	sumall(ind,1)=sum(o)*dz !mol/m3 times volume (with dx=1,dy=1)
	sumall(ind,2)=sum(d)*dz
	sumall(ind,3)=sum(dom)*dz
	sumall(ind,4)=sum(bo)*dz
	sumall(ind,5)=sum(bo_pa)*dz
	sumall(ind,6)=sum(bnh4)*dz
	sumall(ind,7)=sum(bno2)*dz
	sumall(ind,8)=sum(zoo)*dz
	sumall(ind,9)=sum(ntot)*dz
	sumall(ind,10)=sum(nh4)*dz
	sumall(ind,11)=sum(no2)*dz
	sumall(ind,12)=sum(no3)*dz
	sumall(ind,13)=sum(p1)*dz
	sumall(ind,14)=sum(p2)*dz
	sumall(ind,15)=sum(p3)*dz
	sumall(ind,16)=sum(zoo2)*dz
	sumall(ind,17)=sum(zoo3)*dz

end if

!get kA:
call MYRK(nh4,no3,no2,d,dom,o,zoo,zoo2,zoo3,p1,xp1,p2,xp2,p3,xp3, &
				bo,bo_pa,bnh4,bno2, & 
				knh4A,kno3A,kno2A,kdA,kdomA,koA,kzooA,kzoo2A,kzoo3A, &
                kp1A,kxp1A,kp2A,kxp2A,kp3A,kxp3A, &
				kboA,kbo_paA,kbnh4A,kbno2A)

!get yA:
nh4A = nh4 + dt/2D0*knh4A; 
no2A = no2 + dt/2D0*kno2A; 
no3A = no3 + dt/2D0*kno3A; 
boA = bo + dt/2D0*kboA; 
bnh4A = bnh4 + dt/2D0*kbnh4A; 
bno2A = bno2 + dt/2D0*kbno2A; 
dA = d + dt/2D0*kdA; 
oA = o + dt/2D0*koA; 
zooA = zoo + dt/2D0*kzooA; 
zoo2A = zoo2 + dt/2D0*kzoo2A; 
zoo3A = zoo3 + dt/2D0*kzoo3A; 
p1A = p1 + dt/2D0*kp1A;
p2A = p2 + dt/2D0*kp2A;
p3A = p3 + dt/2D0*kp3A;

call MYRK(nh4A,no3A,no2A,dA,domA,oA,zooA,zoo2A,zoo3A,p1A,xp1A,p2A,xp2A,p3A,xp3A, &
				boA,bo_paA,bnh4A,bno2A, & 
				knh4B,kno3B,kno2B,kdB,kdomB,koB,kzooB,kzoo2B,kzoo3B, &
                kp1B,kxp1B,kp2B,kxp2B,kp3B,kxp3B, &
				kboB,kbo_paB,kbnh4B,kbno2B)
	
!get yB:
nh4B = nh4 + dt/2D0*knh4B; 
no2B = no2 + dt/2D0*kno2B; 
no3B = no3 + dt/2D0*kno3B; 
boB = bo + dt/2D0*kboB; 
bnh4B = bnh4 + dt/2D0*kbnh4B; 
bno2B = bno2 + dt/2D0*kbno2B; 
dB = d + dt/2D0*kdB; 
oB = o + dt/2D0*koB; 
zooB = zoo + dt/2D0*kzooB; 
zoo2B = zoo2 + dt/2D0*kzoo2B; 
zoo3B = zoo3 + dt/2D0*kzoo3B; 
p1B = p1 + dt/2D0*kp1B;
p2B = p2 + dt/2D0*kp2B;
p3B = p3 + dt/2D0*kp3B;

call MYRK(nh4B,no3B,no2B,dB,domB,oB,zooB,zoo2B,zoo3B,p1B,xp1B,p2B,xp2B,p3B,xp3B, &
				boB,bo_paB,bnh4B,bno2B, & 
				knh4C,kno3C,kno2C,kdC,kdomC,koC,kzooC,kzoo2C,kzoo3C, &
                kp1C,kxp1C,kp2C,kxp2C,kp3C,kxp3C, &
				kboC,kbo_paC,kbnh4C,kbno2C)
				
!get yC:
nh4C = nh4 + dt*knh4C; 
no2C = no2 + dt*kno2C; 
no3C = no3 + dt*kno3C; 
boC = bo + dt*kboC; 
bnh4C = bnh4 + dt*kbnh4C; 
bno2C = bno2 + dt*kbno2C; 
dC = d + dt*kdC; 
oC = o + dt*koC; 
zooC = zoo + dt*kzooC; 
zoo2C = zoo2 + dt*kzoo2C; 
zoo3C = zoo3 + dt*kzoo3C; 
p1C = p1 + dt*kp1C;
p2C = p2 + dt*kp2C;
p3C = p3 + dt*kp3C;

call MYRK(nh4C,no3C,no2C,dC,domC,oC,zooC,zoo2C,zoo3C,p1C,xp1C,p2C,xp2C,p3C,xp3C, &
				boC,bo_paC,bnh4C,bno2C, & 
				knh4D,kno3D,kno2D,kdD,kdomD,koD,kzooD,kzoo2D,kzoo3D, &
                kp1D,kxp1D,kp2D,kxp2D,kp3D,kxp3D, &
				kboD,kbo_paD,kbnh4D,kbno2D)
	
nh4 = nh4 + dt/6D0*(knh4A + 2D0*knh4B + 2D0*knh4C + knh4D);
no2 = no2 + dt/6D0*(kno2A + 2D0*kno2B + 2D0*kno2C + kno2D);
no3 = no3 + dt/6D0*(kno3A + 2D0*kno3B + 2D0*kno3C + kno3D);
bo = bo + dt/6D0*(kboA + 2D0*kboB + 2D0*kboC + kboD);
bnh4 = bnh4 + dt/6D0*(kbnh4A + 2D0*kbnh4B + 2D0*kbnh4C + kbnh4D);
bno2 = bno2 + dt/6D0*(kbno2A + 2D0*kbno2B + 2D0*kbno2C + kbno2D);
d = d + dt/6D0*(kdA + 2D0*kdB + 2D0*kdC + kdD);
o = o + dt/6D0*(koA + 2D0*koB + 2D0*koC + koD);	
zoo = zoo + dt/6D0*(kzooA + 2D0*kzooB + 2D0*kzooC + kzooD);	
zoo2 = zoo2 + dt/6D0*(kzoo2A + 2D0*kzoo2B + 2D0*kzoo2C + kzoo2D);	
zoo3 = zoo3 + dt/6D0*(kzoo3A + 2D0*kzoo3B + 2D0*kzoo3C + kzoo3D);	
if (onep.eq.0) then
    p1 = p1 + dt/6D0*(kp1A + 2D0*kp1B + 2D0*kp1C + kp1D);		
end if
p2 = p2 + dt/6D0*(kp2A + 2D0*kp2B + 2D0*kp2C + kp2D);
p3 = p3 + dt/6D0*(kp3A + 2D0*kp3B + 2D0*kp3C + kp3D);	


if (recordDaily.eq.1) then

!append at every time step:
print*,t*dt		
	OPEN(UNIT=7,FILE='Iin.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
	WRITE(7,*) (Iin)
	CLOSE(7)

OPEN(UNIT=5,FILE='Iz.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (Iz)
CLOSE(5)	

print*,t*dt		
	OPEN(UNIT=7,FILE='time_all.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
	WRITE(7,*) (t*dt)
	CLOSE(7)	

OPEN(UNIT=5,FILE='nh4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (nh4)
CLOSE(5)	
OPEN(UNIT=5,FILE='no2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (no2)
CLOSE(5)
OPEN(UNIT=5,FILE='no3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (no3)
CLOSE(5)
OPEN(UNIT=5,FILE='d_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (d)
CLOSE(5)
OPEN(UNIT=5,FILE='dom_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (dom)
CLOSE(5)
OPEN(UNIT=5,FILE='o_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (o)
CLOSE(5)	
OPEN(UNIT=5,FILE='bo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (bo)
CLOSE(5)	
OPEN(UNIT=5,FILE='bo_pa_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (bo_pa)
CLOSE(5)	
OPEN(UNIT=5,FILE='bnh4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (bnh4)
CLOSE(5)
OPEN(UNIT=5,FILE='bno2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (bno2)
CLOSE(5)
OPEN(UNIT=5,FILE='ubo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (u_bo)
CLOSE(5)
OPEN(UNIT=5,FILE='ubnh4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (u_bnh4)
CLOSE(5)
OPEN(UNIT=5,FILE='ubno2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (u_bno2)
CLOSE(5)
OPEN(UNIT=5,FILE='up1_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (u_p1)
CLOSE(5)
OPEN(UNIT=5,FILE='up2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (u_p2)
CLOSE(5)
OPEN(UNIT=5,FILE='up3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (u_p3)
CLOSE(5)
OPEN(UNIT=5,FILE='PCmax2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (PCmax2)
CLOSE(5)
OPEN(UNIT=5,FILE='PCmax3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (PCmax3)
CLOSE(5)
OPEN(UNIT=5,FILE='zoo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (zoo)
CLOSE(5)
OPEN(UNIT=5,FILE='zoo2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (zoo2)
CLOSE(5)
OPEN(UNIT=5,FILE='zoo3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (zoo3)
CLOSE(5)
OPEN(UNIT=5,FILE='p1_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p1)
CLOSE(5)	
OPEN(UNIT=5,FILE='xp1_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (xp1)
CLOSE(5)	
OPEN(UNIT=5,FILE='p2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p2)
CLOSE(5)	
OPEN(UNIT=5,FILE='xp2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (xp2)
CLOSE(5)	
OPEN(UNIT=5,FILE='p3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p3)
CLOSE(5)	
OPEN(UNIT=5,FILE='xp3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (xp3)
CLOSE(5)
OPEN(UNIT=5,FILE='Iz_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (Iz)
CLOSE(5)
OPEN(UNIT=5,FILE='chl2c_p3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (chl2c_p3)
CLOSE(5)
OPEN(UNIT=5,FILE='chl2c_p2_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (chl2c_p2)
CLOSE(5)
OPEN(UNIT=5,FILE='Chlt_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (Chlt)
CLOSE(5)
OPEN(UNIT=5,FILE='P3uptakeNH4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (P3uptakeNH4)
CLOSE(5)
OPEN(UNIT=5,FILE='P2uptakeNH4_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (P2uptakeNH4)
CLOSE(5)
OPEN(UNIT=5,FILE='kno2_p3use_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno2_p3use)
CLOSE(5)
OPEN(UNIT=5,FILE='kno2_p2use_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno2_p2use)
CLOSE(5)
OPEN(UNIT=5,FILE='kno3_no2oxid_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno3_no2oxid)
CLOSE(5)
OPEN(UNIT=5,FILE='P3uptakeNO3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (P3uptakeNO3)
CLOSE(5)
OPEN(UNIT=5,FILE='P2uptakeNO3_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (P2uptakeNO3)
CLOSE(5)
OPEN(UNIT=5,FILE='knh4zoo_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (knh4zoo)
CLOSE(5)
OPEN(UNIT=5,FILE='knh4_het_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (knh4_het)
CLOSE(5)
OPEN(UNIT=5,FILE='knh4_nh4oxid_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (knh4_nh4oxid)
CLOSE(5)
OPEN(UNIT=5,FILE='kno2_nh4oxid_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno2_nh4oxid)
CLOSE(5)
OPEN(UNIT=5,FILE='kno2_no2oxid_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno2_no2oxid)
CLOSE(5)
OPEN(UNIT=5,FILE='kno3diff_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno3diff)
CLOSE(5)
OPEN(UNIT=5,FILE='kno2diff_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (kno2diff)
CLOSE(5)
OPEN(UNIT=5,FILE='knh4diff_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (knh4diff)
CLOSE(5)
OPEN(UNIT=5,FILE='p3diff_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p3diff)
CLOSE(5)
OPEN(UNIT=5,FILE='p3growth_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p3growth)
CLOSE(5)
OPEN(UNIT=5,FILE='p3mortality_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p3mortality)
CLOSE(5)
OPEN(UNIT=5,FILE='p3grazed_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p3grazed)
CLOSE(5)
OPEN(UNIT=5,FILE='p2growth_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p2growth)
CLOSE(5)
OPEN(UNIT=5,FILE='p2mortality_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p2mortality)
CLOSE(5)
OPEN(UNIT=5,FILE='p2grazed_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (p2grazed)
CLOSE(5)
OPEN(UNIT=5,FILE='dsinking_fa.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
WRITE(5,*) (dsinking)
CLOSE(5)
end if

if (MOD(t*dt,1.00).eq.0) then
	print*,t*dt		
	OPEN(UNIT=7,FILE='time_record.txt',ACCESS='SEQUENTIAL',BLANK='ZERO',POSITION='APPEND')
	WRITE(7,*) (t*dt)
	CLOSE(7)	
end if

if ((MOD(t*dt,dayint).eq.0).OR.(t*dt.eq.ndays)) then

    
OPEN(UNIT=6,FILE='chl2c_p1.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (chl2c_p1(J),J=1,nz+4)
CLOSE(6)
OPEN(UNIT=6,FILE='chl2c_p2.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (chl2c_p2(J),J=1,nz+4)
CLOSE(6)
OPEN(UNIT=6,FILE='chl2c_p3.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (chl2c_p3(J),J=1,nz+4)
CLOSE(6)
OPEN(UNIT=6,FILE='chl2c.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (chl2c(J),J=1,nz+4)
CLOSE(6)

!NOTE: using no3uptakeP as a placeholder for recording multiple quantities for N fluxes:
!diff
    do j=1,nz ; jc=j+2;
        call mydiff(no2,Kz,j,dz,nz,diff)
            kno2diff(jc)=diff
    end do
OPEN(UNIT=6,FILE='kno2_diff.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (kno2diff(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='knh4zoo.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (knh4zoo(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='knh4_het.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (knh4_het(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='knh4_nh4oxid.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (knh4_nh4oxid(J),J=1,nz+4)
CLOSE(6)

!source: NH4 oxidizer:
OPEN(UNIT=6,FILE='kno2_nh4oxid.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (kno2_nh4oxid(J),J=1,nz+4)
CLOSE(6)

!sink: NO2 oxidizer:

OPEN(UNIT=6,FILE='kno2_no2oxid.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (kno2_no2oxid(J),J=1,nz+4)
CLOSE(6)

!source: phytopl 3 emit:
OPEN(UNIT=6,FILE='kno2_p3emit.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no2emitP(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='kno3_no2oxid.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (kno3_no2oxid(J),J=1,nz+4)
CLOSE(6)


!!now, the pp uptake of each N:
!no3 uptake by pp3
!more than based on just u_p bc of inefficiency
no3uptakeP=-u_p3*p3*limno3p3/(nlimtotp3+1D-38)
OPEN(UNIT=6,FILE='P3uptakeNO3.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3uptakeP(J),J=1,nz+4)
CLOSE(6)

no3uptakeP=-u_p3*p3*limno2p3/(nlimtotp3+1D-38)
OPEN(UNIT=6,FILE='P3uptakeNO2.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3uptakeP(J),J=1,nz+4)
CLOSE(6)

!nh4 uptake by pp3: (still using no3uptake as placeholder): (this is redundant with above kno2_puse.txt)
no3uptakeP=-u_p3*p3*limnh4p3/(nlimtotp3+1D-38)
OPEN(UNIT=6,FILE='P3uptakeNH4.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3uptakeP(J),J=1,nz+4)
CLOSE(6)

no3uptakeP=-u_p2*p2*limno3p2/(nlimtotp2+1D-38)
OPEN(UNIT=6,FILE='P2uptakeNO3.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3uptakeP(J),J=1,nz+4)
CLOSE(6)

!no2 uptake by pp2: (still using no3uptake as placeholder): (this is redundant with above kno2_puse.txt)
no3uptakeP=-u_p2*p2*limno2p2/(nlimtotp2+1D-38)
OPEN(UNIT=6,FILE='P2uptakeNO2.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3uptakeP(J),J=1,nz+4)
CLOSE(6)

!no2 uptake by pp3: (still using no3uptake as placeholder): (this is redundant with above kno2_puse.txt)
no3uptakeP=-u_p2*p2*limnh4p2/(nlimtotp2+1D-38)
OPEN(UNIT=6,FILE='P2uptakeNH4.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3uptakeP(J),J=1,nz+4)
CLOSE(6)

!p3growth
!P3growth=u_p3*p3!*limnh4/(nlimtot+1D-38)
OPEN(UNIT=6,FILE='P3growth.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (P3growth(J),J=1,nz+4)
CLOSE(6)

!p3mortality
!P3mortality=-p3*mlins*TempFun!*limnh4/(nlimtot+1D-38)
!OPEN(UNIT=6,FILE='P3mortality.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
!WRITE(6,*) (P3mortality(J),J=1,nz+4)
!CLOSE(6)

!p3 grazed by zoo
!P3grazed=-p3*g3*zoo3/(bt+pt+1D-38)!*limnh4/(nlimtot+1D-38)
!OPEN(UNIT=6,FILE='P3grazed.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
!WRITE(6,*) (P3grazed(J),J=1,nz+4)
!CLOSE(6)

!p2growth
!P2growth=u_p2*p2!*limnh4/(nlimtot+1D-38)
OPEN(UNIT=6,FILE='P2growth.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (P2growth(J),J=1,nz+4)
CLOSE(6)

!p2mortality
!P2mortality=-p2*mlins*TempFun!*limnh4/(nlimtot+1D-38)
!OPEN(UNIT=6,FILE='P3mortality.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
!WRITE(6,*) (P3mortality(J),J=1,nz+4)
!CLOSE(6)

!p2 grazed by zoo
!P2grazed=-p2*g3*zoo3/(bt+pt+1D-38)!*limnh4/(nlimtot+1D-38)
!OPEN(UNIT=6,FILE='P3grazed.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
!WRITE(6,*) (P3grazed(J),J=1,nz+4)
!CLOSE(6)



!also record diffusion of nitrate and ammonium:
    do j=1,nz ; jc=j+2;
        call mydiff(no3,Kz,j,dz,nz,diff)
            kno3diff(jc)=diff
    end do
OPEN(UNIT=6,FILE='kno3_diff.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (kno3diff(J),J=1,nz+4)
CLOSE(6)

    do j=1,nz ; jc=j+2;
        call mydiff(nh4,Kz,j,dz,nz,diff)
            knh4diff(jc)=diff
    end do
OPEN(UNIT=6,FILE='knh4_diff.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(*,*) (knh4diff(J),J=1,nz+4)
CLOSE(6)


    do j=1,nz ; jc=j+2;
        call mydiff(p3,Kz,j,dz,nz,diff)
            p3diff(jc)=diff
    end do
OPEN(UNIT=6,FILE='p3_diff.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (p3diff(J),J=1,nz+4)
CLOSE(6)

    do j=1,nz ; jc=j+2;
        call mydiff(p2,Kz,j,dz,nz,diff)
            p2diff(jc)=diff
    end do
OPEN(UNIT=6,FILE='p2_diff.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (p2diff(J),J=1,nz+4)
CLOSE(6)

    do j=1,nz ; jc=j+2;
        call myquick(d,wd,j,dz,nz,adv)
            dsinking(jc)=adv
    end do
OPEN(UNIT=6,FILE='d_sinking.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (dsinking(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='wd.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (wd(J),J=1,nz+1)
CLOSE(6)

OPEN(UNIT=6,FILE='kz.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (kz(J),J=1,nz+1)
CLOSE(6)

OPEN(UNIT=6,FILE='Iz.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (Iz(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='Chlt_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (Chlt(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='nh4_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (nh4(J),J=1,nz+4)
CLOSE(6)
	
OPEN(UNIT=6,FILE='no2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no2(J),J=1,nz+4)
CLOSE(6)
	
OPEN(UNIT=6,FILE='no3_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (no3(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='d_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (d(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='dom_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (dom(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='o_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (o(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='bo_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (bo(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='ubo_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (u_bo(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='ubnh4_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (u_bnh4(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='ubno2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (u_bno2(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='up1_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (u_p1(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='up2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (u_p2(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='up3_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (u_p3(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='bo_pa_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (bo_pa(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='bnh4_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (bnh4(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='bno2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (bno2(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='zoo_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (zoo(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='zoo2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (zoo2(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='zoo3_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (zoo3(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='p1_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (p1(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='xp1_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (xp1(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='p2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (p2(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='xp2_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (xp2(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='p3_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (p3(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='xp3_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
WRITE(6,*) (xp3(J),J=1,nz+4)
CLOSE(6)

OPEN(UNIT=6,FILE='time_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
DO J=1,ind
WRITE(6,*) (time(J))
END DO
CLOSE(6)

OPEN(UNIT=6,FILE='z_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
DO I=1,nz
WRITE(6,*) (zm(I))
END DO
CLOSE(6)

OPEN(UNIT=6,FILE='sumall_f.txt',ACCESS='SEQUENTIAL',BLANK='ZERO')
DO I=1,ind
WRITE(6,*) (sumall(I,J),J=1,17)
END DO
CLOSE(6)

	end if  !end the mod

end do !!end time loop

print*,'Total CPU time in seconds:'
call CPU_TIME(cputime)
print*,cputime


contains
SUBROUTINE MYQUICK(C,w,j,dz,nz,adv)
implicit none
REAL*8 :: C(nz+4),w(nz+1),adv
REAL*8 :: wp1,wn1,wp,wn,Dy1,Dy2,Dyn1,Fu,Fd
INTEGER :: j,nz,dz
INTEGER :: jc

jc=j+2

        !at top face:
        wp1=(w(j+1)+abs(w(j+1)))/2D0;
        wn1=(w(j+1)-abs(w(j+1)))/2D0;
        !at bottom face:
        wp=(w(j)+abs(w(j)))/2D0;
        wn=(w(j)-abs(w(j)))/2D0;
          
        Dy1=C(jc+2)-2D0*C(jc+1)+C(jc);
        Dy2=C(jc+1)-2D0*C(jc)+C(jc-1);
        Dyn1=C(jc)-2D0*C(jc-1)+C(jc-2);

        Fu=w(j+1)/2D0*(C(jc)+C(jc+1)) - wp1/8D0*Dy2 - wn1/8D0*Dy1;
        Fd=w(j)/2D0*(C(jc-1)+C(jc)) - wp/8D0*Dyn1 - wn/8D0*Dy2;
                
		adv=(Fu-Fd)/dz;  
        
END SUBROUTINE MYQUICK

SUBROUTINE MYDIFF(C,Kz,j,dz,nz,diff)
implicit none
REAL*8 :: C(nz+4),Kz(nz+1),diff
REAL*8 :: Fu,Fd
INTEGER :: j,nz,dz
INTEGER :: jc

jc=j+2
        
        Fu=Kz(j+1)*(C(jc+1)-C(jc))/dz;
        Fd=Kz(j)*(C(jc)-C(jc-1))/dz;
               
        diff=(Fu-Fd)/dz;
        
END SUBROUTINE MYDIFF


SUBROUTINE MYRK(nh4_one,no3_one,no2_one,d_one,dom_one,o_one, &
                zoo_one,zoo2_one,zoo3_one, &
				p1_one,xp1_one,p2_one,xp2_one,p3_one,xp3_one, &
				bo_one,bo_pa_one,bnh4_one,bno2_one, & 
				knh4_two,kno3_two,kno2_two,kd_two,kdom_two,ko_two, &
                kzoo_two,kzoo2_two,kzoo3_two, &
				kp1_two,kxp1_two,kp2_two,kxp2_two,kp3_two,kxp3_two, &
				kbo_two,kbo_pa_two,kbnh4_two,kbno2_two)
				
implicit none
REAL*8, dimension(nz+4), intent(in) :: nh4_one,no3_one,no2_one,d_one,dom_one,o_one, &
				zoo_one,zoo2_one,zoo3_one,p1_one,xp1_one,p2_one,xp2_one,p3_one,xp3_one, &
				bo_one,bo_pa_one,bnh4_one,bno2_one
REAL*8, dimension(nz+4), intent(out) :: knh4_two,kno3_two,kno2_two,kd_two, &
				kdom_two,ko_two,kzoo_two,kzoo2_two,kzoo3_two, &
                kp1_two,kxp1_two,kp2_two,kxp2_two,kp3_two,kxp3_two, &
				kbo_two,kbo_pa_two,kbnh4_two,kbno2_two

    do j=1,nz ; jc=j+2;       
    	call mydiff(nh4_one,Kz,j,dz,nz,diff)
			knh4_two(jc)=diff
			call mydiff(no2_one,Kz,j,dz,nz,diff)
			kno2_two(jc)=diff
			call mydiff(no3_one,Kz,j,dz,nz,diff)
            kno3_two(jc)=diff
			call mydiff(bo_one,Kz,j,dz,nz,diff)
			kbo_two(jc)=diff
		    call myquick(bo_pa_one,wd,j,dz,nz,adv)
			call mydiff(bo_pa_one,Kz,j,dz,nz,diff)
        	kbo_pa_two(jc)=-adv+diff
        	call mydiff(bnh4_one,Kz,j,dz,nz,diff)
        	kbnh4_two(jc)=diff
        	call mydiff(bno2_one,Kz,j,dz,nz,diff)
        	kbno2_two(jc)=diff
        	call myquick(d_one,wd,j,dz,nz,adv)
        	call mydiff(d_one,Kz,j,dz,nz,diff)
        	kd_two(jc)=-adv+diff
        	call mydiff(dom_one,Kz,j,dz,nz,diff)
        	kdom_two(jc)=diff
        	call mydiff(o_one,KzO,j,dz,nz,diff)
        	ko_two(jc)=diff
        	call mydiff(zoo_one,Kz,j,dz,nz,diff)
        	kzoo_two(jc)=diff
        if (onep.eq.0) then
            call mydiff(p1_one,Kz,j,dz,nz,diff)
        	kp1_two(jc)=diff
        	call mydiff(xp1_one,Kz,j,dz,nz,diff)
        	kxp1_two(jc)=diff
        end if
		    call mydiff(p2_one,Kz,j,dz,nz,diff)
        	kp2_two(jc)=diff
        	call mydiff(xp2_one,Kz,j,dz,nz,diff)
        	kxp2_two(jc)=diff
            call mydiff(p3_one,Kz,j,dz,nz,diff)
        	kp3_two(jc)=diff
        	call mydiff(xp3_one,Kz,j,dz,nz,diff)
        	kxp3_two(jc)=diff
        	call mydiff(zoo2_one,Kz,j,dz,nz,diff)
        	kzoo2_two(jc)=diff
        	call mydiff(zoo3_one,Kz,j,dz,nz,diff)
        	kzoo3_two(jc)=diff

end do

bt=bo_one+bnh4_one+bno2_one
pt=p1_one+p2_one+p3_one
btsq=bo_one*bo_one+bnh4_one*bnh4_one+bno2_one*bno2_one
ptsq=p1_one*p1_one+p2_one*p2_one+p3_one*p3_one

!uptake limitations for bacteria/archaea:
po=po_coef*o_one*TempFun 
pd=pd_max*(d_one/(d_one+kd))*TempFun 

!do j=1,nz+4
!if (nh4_one<=koxid) then
!limnh4b=(nh4_one/(nh4_one+kn*(1+exp(kna*log10(Iz)+knb))))!*TempFun
!else
!limnh4b=0D0
!end if
!end do
limnh4b=(nh4_one/(nh4_one+kn*(1+exp(kna*log10(Iz)+knb))))!*TempFun
limno2b=(no2_one/(no2_one+kn_noo*(1+exp(kn_nooa*log10(Iz)+kn_noob))))!*TempFun

!pnh4b=pn_max*limnh4b*TempFun 
!pno2b=pn_max_noo*limno2b*TempFun 
!now with no Temp: Horak 2013
pnh4b=pn_max*max((1-pna*Iz),0D0)*limnh4b 
pno2b=pn_max_noo*max((1-pn_nooa*Iz),0D0)*limno2b 

!Bacteria growth rates:

u_bo=min(po*yo_bo,pd*yd_bo)
u_bnh4=max(min(pnh4b*ynh4_bnh4,po*yo_bnh4),0D0)
u_bno2=min(pno2b*yno2_bno2,po*yo_bno2)

!uptake limitations for phytopp setting the threshold for uptake
!for nh4, uptake can only happen when its concentration higher than 10 nM
do j=1,nz;jc=j+2;
    if (nh4_one(jc) <= 1D-6 .and. no2_one(jc) <= 1D-6) then
        if (no3_one(jc) <= 1D-6) then
            limnh4p3(jc)=0D0
            limno2p3(jc)=0D0
            limno3p3(jc)=0D0
            nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
        else
            limnh4p3(jc)=0D0
            limno2p3(jc)=0D0
            limno3p3(jc)=(no3_one(jc)/(no3_one(jc)+kno3p3))
            nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
        end if
    else if (nh4_one(jc) <= 1D-6 .and. no2_one(jc) > 1D-6) then
         if (no3_one(jc) <= 1D-6) then
             limnh4p3(jc)=0D0
             limno2p3(jc)=(no2_one(jc)/(no2_one(jc)+kno2p3))
             limno3p3(jc)=0D0
             nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
         else
             limnh4p3(jc)=0D0
             limno2p3(jc)=(no2_one(jc)/(no2_one(jc)+kno2p3))
             limno3p3(jc)=(no3_one(jc)/(no3_one(jc)+kno3p3))
             nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
         end if
    else if (nh4_one(jc) > 1D-6 .and. no2_one(jc) > 1D-6) then
         if (no3_one(jc) <= 1D-6) then
             limnh4p3(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p3))
             limno2p3(jc)=(no2_one(jc)/(no2_one(jc)+kno2p3))
             limno3p3(jc)=0D0
             nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
         else
             limnh4p3(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p3))
             limno2p3(jc)=(no2_one(jc)/(no2_one(jc)+kno2p3))
             limno3p3(jc)=(no3_one(jc)/(no3_one(jc)+kno3p3))
             nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
          end if
    else if (nh4_one(jc) > 1D-6 .and. no2_one(jc) <= 1D-6) then
         if (no3_one(jc) <= 1D-6) then
             limnh4p3(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p3))
             limno2p3(jc)=0D0
             limno3p3(jc)=0D0
             nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
         else
             limnh4p3(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p3))
             limno2p3(jc)=0D0
             limno3p3(jc)=(no3_one(jc)/(no3_one(jc)+kno3p3))
             nlimtotp3(jc)=min(1D0,limnh4p3(jc)+limno2p3(jc)+limno3p3(jc))
         end if
    end if
end do
do j=1,nz;jc=j+2;
    if (nh4_one(jc) <= 1D-6 .and. no2_one(jc) <= 1D-6) then
        if (no3_one(jc) <= 1D-6) then
	        limnh4p2(jc)=0D0
            limno2p2(jc)=0D0
            limno3p2(jc)=0D0
            nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			!nutri(jc)=1
        else
	        limnh4p2(jc)=0D0
            limno2p2(jc)=0D0
            limno3p2(jc)=(no3_one(jc)/(no3_one(jc)+kno3p2))
            nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			!nutri(jc)=2
        end if
    else if (nh4_one(jc) <= 1D-6 .and. no2_one(jc) > 1D-6) then
         if (no3_one(jc) <= 1D-6) then
	         limnh4p2(jc)=0D0
             limno2p2(jc)=(no2_one(jc)/(no2_one(jc)+kno2p2))
             limno3p2(jc)=0D0
             nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			 !nutri(jc)=3
         else
	         limnh4p2(jc)=0D0
             limno2p2(jc)=(no2_one(jc)/(no2_one(jc)+kno2p2))
             limno3p2(jc)=(no3_one(jc)/(no3_one(jc)+kno3p2))
             nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			 !nutri(jc)=4
         end if
    else if (nh4_one(jc) > 1D-6 .and. no2_one(jc) > 1D-6) then
         if (no3_one(jc) <= 1D-6) then
	         limnh4p2(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p2))
             limno2p2(jc)=(no2_one(jc)/(no2_one(jc)+kno2p2))
             limno3p2(jc)=0D0
             nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			 !nutri(jc)=5
         else
	         limnh4p2(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p2))
             limno2p2(jc)=(no2_one(jc)/(no2_one(jc)+kno2p2))
             limno3p2(jc)=(no3_one(jc)/(no3_one(jc)+kno3p2))
             nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			 !nutri(jc)=6
          end if
    else if (nh4_one(jc) > 1D-6 .and. no2_one(jc) <= 1D-6) then
         if (no3_one(jc) <= 1D-6) then
	         limnh4p2(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p2))
             limno2p2(jc)=0D0
             limno3p2(jc)=0D0
             nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			 !nutri(jc)=7
         else
	         limnh4p2(jc)=(nh4_one(jc)/(nh4_one(jc)+knh4p2))
             limno2p2(jc)=0D0
             limno3p2(jc)=(no3_one(jc)/(no3_one(jc)+kno3p2))
             nlimtotp2(jc)=min(1D0,limnh4p2(jc)+limno2p2(jc)+limno3p2(jc))
			 !nutri(jc)=8
         end if
    end if
end do

!Geider chlorophyll:c based growth rates:
PCmax1 = max(1D0*umaxp*TempFun*limnh4p3,1D-38)
PCmax2 = max(1D0*umaxp*TempFun*nlimtotp2,1D-38)!min(1D0,limnh4+limno2)
PCmax3 = max(1D0*umaxp*TempFun*nlimtotp3,1D-38)
a_Is = phimaxs*a_chl*Iz*convI !mmol C/mol Ein * m2/mg chla * Ein/m2/d = mmol C/mg chla/d
a_Il = phimaxl*a_chl*Iz*convI 
chl2c_p1 = max(chl2cmin, min(chl2cmax, chl2cmax/(1D0+chl2cmax*a_Is/2D0/PCmax1)))
chl2c_p2 = max(chl2cmin, min(chl2cmax, chl2cmax/(1D0+chl2cmax*a_Il/2D0/PCmax2)))
chl2c_p3 = max(chl2cmin, min(chl2cmax, chl2cmax/(1D0+chl2cmax*a_Is/2D0/PCmax3)))
chl2c = chl2c_p3
PC1 = PCmax1*(1D0 - exp(-a_Is*chl2c_p1/PCmax1))
PC2 = PCmax2*(1D0 - exp(-a_Il*chl2c_p2/PCmax2))
PC3 = PCmax3*(1D0 - exp(-a_Is*chl2c_p3/PCmax3))

u_p1=PC1
u_p2=PC2
u_p3=PC3

!grazing: type II
!g=gmax*bt/(bt+kg)*TempFun !for zoo
!g2=gmax*pt/(pt+kg)*TempFun !for zoo2
g3=gmax*(bt+pt)/(bt+pt+kg)*TempFun !for zoo3 (goal: ONLY this one)
!zeta1=0.25*bo_one/(0.25*bo_one+0.25*bnh4_one+0.25*bno2_one+0.25*p3_one)
!zeta2=0.25*bnh4_one/(0.25*bo_one+0.25*bnh4_one+0.25*bno2_one+0.25*p3_one)
!zeta3=0.25*bno2_one/(0.25*bo_one+0.25*bnh4_one+0.25*bno2_one+0.25*p3_one)
!zeta4=0.25*p3_one/(0.25*bo_one+0.25*bnh4_one+0.25*bno2_one+0.25*p3_one)
!g3=gmax*(zeta1*bo_one+zeta2*bnh4_one+zeta3*bno2_one+zeta4*p3_one) &
!/(zeta1*bo_one+zeta2*bnh4_one+zeta3*bno2_one+zeta4*p3_one+kg)*TempFun
knh4zoo=(1D0-gam)*g3*zoo3_one
knh4_het=enh4_bo*u_bo*bo_one
knh4_nh4oxid=-1D0/ynh4_bnh4*u_bnh4*bnh4_one
kno2_nh4oxid=eno2_bnh4*u_bnh4*bnh4_one
kno2_no2oxid=-1/yno2_bno2*u_bno2*bno2_one
kno2_p3use=-u_p3*p3_one*limno2p3/(nlimtotp3+1D-38)
kno2_p2use=-u_p2*p2_one*limno2p2/(nlimtotp2+1D-38)
kno3_no2oxid=eno3_bno2*u_bno2*bno2_one
P3uptakeNH4=-u_p3*p3_one*limnh4p3/(nlimtotp3+1D-38)
P3uptakeNO2=-u_p3*p3_one*limno2p3/(nlimtotp3+1D-38)
P3uptakeNO3=-u_p3*p3_one*limno3p3/(nlimtotp3+1D-38)
P2uptakeNH4=-u_p2*p2_one*limnh4p2/(nlimtotp2+1D-38)
P2uptakeNO2=-u_p2*p2_one*limno2p2/(nlimtotp2+1D-38)
P2uptakeNO3=-u_p2*p2_one*limno3p2/(nlimtotp2+1D-38)
P3growth=u_p3*p3_one
P2growth=u_p2*p2_one
!nh4tt_1=nh4_one/(enh4_bo*u_bo*bo_one+ (1D0-gam)*g3*zoo3_one)
!nh4tt_2=nh4_one/(P3uptakeNH4+P2uptakeNH4+knh4_nh4oxid) 
!no2tt_1=no2_one/kno2_nh4oxid
!no2tt_2=no2_one/(kno2_p3use+kno2_p2use+kno2_no2oxid) !cal the turnovertime of no2 
!no3tt_1=no3_one/(eno3_bno2*u_bno2*bno2_one)
!no3tt_2=no3_one/(P3uptakeNO3+P2uptakeNO3) 


!EQUATIONS:

knh4_two = knh4_two &
			+ enh4_bo*u_bo*bo_one & !2 aerobic hets
            + (1D0-gam)*g*zoo_one &  !zoo
			+ (1D0-gam)*g2*zoo2_one  & !zoo2
			+ (1D0-gam)*g3*zoo3_one &  !zoo
			- 1D0/ynh4_bnh4*u_bnh4*bnh4_one & !consumption: NH4 oxidizer 
			- u_p1*p1_one & 
            - u_p2*p2_one*limnh4p2/(nlimtotp2+1D-38) &
            - u_p3*p3_one*limnh4p3/(nlimtotp3+1D-38) 

kno2_two = kno2_two &
			+ eno2_bnh4*u_bnh4*bnh4_one & !source: NH4 oxidizer 
			- 1D0/yno2_bno2*u_bno2*bno2_one & !sink: aerobic NO2 oxidizer
            - u_p2*p2_one*limno2p2/(nlimtotp2+1D-38) & !pp
            - u_p3*p3_one*limno2p3/(nlimtotp3+1D-38) 
		
kno3_two = kno3_two &
			+ eno3_bno2*u_bno2*bno2_one & !source: aerobic NO2 oxidizer
            - u_p2*p2_one*limno3p2/(nlimtotp2+1D-38) &
            - u_p3*p3_one*limno3p3/(nlimtotp3+1D-38)
            
kbo_two= kbo_two +  bo_one*(u_bo - mlin*TempFun - mquad*bo_one*TempFun - g*zoo_one/(bt+1D-38) &
         - g3*zoo3_one/(bt+pt+1D-38)) 
kbnh4_two= kbnh4_two +  bnh4_one*(u_bnh4 - mlin*TempFun - mquad*bnh4_one*TempFun - g*zoo_one/(bt+1D-38) &
           - g3*zoo3_one/(bt+pt+1D-38))
kbno2_two= kbno2_two +  bno2_one*(u_bno2 - mlin*TempFun - mquad*bno2_one*TempFun - g*zoo_one/(bt+1D-38) &
           - g3*zoo3_one/(bt+pt+1D-38))

kp1_two = kp1_two + p1_one*(u_p1 - mlin*TempFun - mquad*p1_one*TempFun - g2*zoo2_one/(pt+1D-38) - g3*zoo3_one/(bt+pt+1D-38))
kp2_two = kp2_two + p2_one*(u_p2 - mlinl*TempFun - mquad*p2_one*TempFun - g2*zoo2_one/(pt+1D-38) - g3*zoo3_one/(bt+pt+1D-38))
kp3_two = kp3_two + p3_one*(u_p3 - mlins*TempFun - mquad*p3_one*TempFun - g2*zoo2_one/(pt+1D-38) - g3*zoo3_one/(bt+pt+1D-38))

kzoo_two=kzoo_two + gam*g*zoo_one - mz*zoo_one*zoo_one*TempFun
kzoo2_two=kzoo2_two + gam*g2*zoo2_one - mz*zoo2_one*zoo2_one*TempFun
kzoo3_two=kzoo3_two + gam*g3*zoo3_one - mz*zoo3_one*zoo3_one*TempFun

kd_two= kd_two &
		+ mlin*bt*TempFun &
        + (mlinl*p2_one+mlins*p3_one)*TempFun &
		+ mquad*(btsq+ptsq)*TempFun &
		+ mz*zoo_one*zoo_one*TempFun &!quadratic
		+ mz*zoo2_one*zoo2_one*TempFun &!quadratic
		+ mz*zoo3_one*zoo3_one*TempFun & !quadratic
		- 1D0/yd_bo*u_bo*bo_one !sink: 1 heterotroph

ko_two = ko_two &
		+ RredO*(u_p1*p1_one + u_p2*p2_one + u_p3*p3_one) & !pp production
        - RredO*(1D0-gam)*g*zoo_one & !zoo use
		- RredO*(1D0-gam)*g2*zoo2_one & !zoo2 use
		- RredO*(1D0-gam)*g3*zoo3_one & !zoo2 use
		- 1D0/yo_bo*u_bo*bo_one & !het B use
		- 1D0/yo_bnh4*u_bnh4*bnh4_one & !NH4 oxid use
		- 1D0/yo_bno2*u_bno2*bno2_one & !NO2 oxid use
		+ koverh*(o2sat-o_one)*eqmask & !air-sea
		+ t_o2relax*(o2satdeep-o_one)*inmask  !relaxation at depth (lateral flux)


        
END SUBROUTINE MYRK

END PROGRAM MGbasedonEZM


